import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RegistationForm from "components/organisms/pageDesign/Registationform";
import DottedConnector from "components/organisms/pageDesign/DottedConnector";
import { Box } from "@mui/material";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
        <meta charSet="utf-8"></meta>
      </head>

      <body className={inter.className}>
          <Box>
            {/* <Navgation /> */}
            {/* Registation Form */}
            <DottedConnector />
            <RegistationForm />
          </Box>
      </body>
    </html>
  );
}
